# Generated by Django 5.2 on 2025-09-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
