# Generated by Django 5.2 on 2025-09-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_paciente_fecha_nacimiento_and_more'),
        ('gestion', '0002_passwordresetcode'),
    ]

    operations = [
    ]
