# Generated by Django 5.2 on 2025-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(default='1900-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
