# Generated by Django 5.2.6 on 2026-05-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico_tratante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='prevision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('presupuesto', 'Presupuesto')], default='consulta', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada'), ('Pagado', 'Pagado')], default='Agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.profesional'),
        ),
    ]
