# Generated by Django 5.2.6 on 2026-05-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_cita_comuna_cita_documento_cita_medico_tratante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('medico_tratante', models.CharField(blank=True, max_length=200)),
                ('prevision', models.CharField(blank=True, max_length=100)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
