# Generated by Django 5.2.6 on 2026-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profesionales/'),
        ),
    ]
