# Generated by Django 5.2.6 on 2026-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_profesional_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='indicaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Confirmada', 'Confirmada'), ('En curso', 'En curso'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada'), ('Pagado', 'Pagado')], default='Agendada', max_length=20),
        ),
    ]
